// Gallery netdisk bridge — JDownloader Event Scripter.
//
// Generated by Gallery (维护 → 下载 → 连接脚本). Regenerate from there instead of
// editing this copy: the pairing token is per-install, and the protocol version
// has to match the Gallery that issued it.
//
// Trigger: Interval, 10000 ms.
//
// What this script is and is not:
//   * It reports state and applies Gallery's commands. It never waits for a
//     transfer: JD owns the download, this only observes it.
//   * It only ever touches packages whose name starts with "gallery-". Other
//     people's downloads are never paused, started or removed by this script.
//   * Everything it reads from callAPI goes through safeId() first. JD hands a
//     Java long to JavaScript as a number, so an id above 2^53 arrives already
//     rounded; such an id is reported as unusable instead of being used to
//     control a neighbouring task.
//   * An INTERVAL trigger re-evaluates the whole script body on every tick, so
//     no value may live in a plain variable between ticks. Sequence number,
//     handshake flag, executed command ids and page cursors are all kept in JD
//     properties, which is the only per-run storage the Event Scripter offers.
//   * The protocol is ES5 on purpose. The Event Scripter engine is not a
//     browser, and `let`/arrow functions are not guaranteed there.
//   * One exchange request has a hard 5 second budget whenever JD's Java
//     runtime is reachable; a hung Gallery can then no longer pin the tick.
//     Without that runtime the script falls back to plain postPage and reports
//     request_timeout_ms = 0, which means "no hard timeout", not "bounded".

var GALLERY_TOKEN = "__GALLERY_BRIDGE_TOKEN__";
var GALLERY_URL = "__GALLERY_BRIDGE_URL__";
var GALLERY_PROTOCOL = "__GALLERY_BRIDGE_PROTOCOL__";
var GALLERY_SCRIPT_VERSION = "__GALLERY_BRIDGE_SCRIPT_VERSION__";
var GALLERY_PACKAGE_PREFIX = "gallery-";
var GALLERY_PAGE_SIZE = 100;
var GALLERY_PAGES_PER_TICK = 3;
var GALLERY_MAX_PAGES = 200;
var GALLERY_SAFE_INT = 9007199254740991;
// How many command identities are remembered for de-duplication. Bounded so a
// long-running JD cannot grow the property without limit.
var GALLERY_EXECUTED_MEMORY = 200;
// The wall-clock budget for one exchange request. postPage blocks until the
// server answers and has no timeout of its own: a hung Gallery would pin the
// INTERVAL trigger thread forever and stop every later tick with it.
var GALLERY_REQUEST_BUDGET_MS = 5000;

(function () {
    "use strict";

    function prop(name, fallback) {
        try {
            var value = getProperty(name, false);
            if (value === null || value === undefined || value === "") {
                return fallback;
            }
            return value;
        } catch (e) {
            return fallback;
        }
    }

    function setProp(name, value) {
        try {
            setProperty(name, value, false);
        } catch (e) {
            // setProperty only survives until JD exits. Losing it means the
            // next tick re-handshakes, which Gallery treats as a new session
            // and reconciles rather than as an attack.
        }
    }

    function readCount(name, fallback) {
        var parsed = parseInt(String(prop(name, "")), 10);
        if (!isFinite(parsed) || parsed < 0) {
            return fallback;
        }
        return parsed;
    }

    // A per-install identity plus a per-run session. A restart therefore shows
    // up as a new session on the same bridge, which is what Gallery needs in
    // order to re-adopt the tasks this run owns.
    function identity() {
        var device = "jd-local";
        var session = prop("gallery_bridge_session_id", "");
        if (!session) {
            session = device + "-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 6);
            setProp("gallery_bridge_session_id", session);
        }
        return {device: device, session: session};
    }

    // JD serialises a Java long into a JS number before this script sees it, so
    // anything above 2^53 has already lost precision. Returning null keeps the
    // caller from acting on a rounded id; the record is still reported so
    // Gallery can show it as needing attention rather than silently dropping it.
    function safeId(value) {
        if (value === null || value === undefined) {
            return null;
        }
        if (typeof value === "number") {
            if (!isFinite(value) || Math.abs(value) > GALLERY_SAFE_INT) {
                return null;
            }
            return String(value);
        }
        var text = String(value);
        if (text === "") {
            return null;
        }
        if (/^-?[0-9]+$/.test(text)) {
            var parsed = Number(text);
            if (!isFinite(parsed) || Math.abs(parsed) > GALLERY_SAFE_INT) {
                return null;
            }
        }
        return text;
    }

    function numberOrZero(value) {
        var n = Number(value);
        return isFinite(n) && n >= 0 ? n : 0;
    }

    // JD's global "auto start" switch for the link collector, read for Gallery's
    // pre-check before any link is moved into the download list.
    //
    // moveToDownloadlist builds its MoveLinksSettings with
    // CFG_LINKGRABBER.LINKGRABBER_AUTO_START_ENABLED, so a move performed while
    // that switch is on starts whatever else the user has queued — this script
    // cannot isolate it by only naming its own UUIDs. Gallery therefore refuses
    // to move anything in until this reads exactly false.
    //
    // Reported as null when the value cannot be read, and null is *not* "off":
    // the two states are different, and only one of them is safe. Returning null
    // blocks the move, so a JD whose configuration this script cannot read
    // degrades to "move stopped, fix it in JD" rather than to a silent
    // start-everything. This script never writes the setting.
    function globalAutoStart() {
        try {
            var raw = callAPI("config", "get",
                "org.jdownloader.gui.views.linkgrabber.addlinksdialog.LinkgrabberSettings",
                null, "LinkgrabberAutoStartEnabled");
            if (raw === true || raw === false) {
                return raw;
            }
            if (raw === null || raw === undefined || raw === "") {
                return null;
            }
            var text = String(raw).toLowerCase();
            if (text === "true") {
                return true;
            }
            if (text === "false") {
                return false;
            }
            return null;
        } catch (error) {
            return null;
        }
    }

    function str(value) {
        return value === null || value === undefined ? "" : String(value);
    }

    function copy(target, source) {
        for (var key in source) {
            if (Object.prototype.hasOwnProperty.call(source, key)) {
                target[key] = source[key];
            }
        }
        return target;
    }

    function loadState() {
        var raw = String(prop("gallery_bridge_executed", ""));
        return {
            seq: readCount("gallery_bridge_seq", 0),
            handshaked: String(prop("gallery_bridge_handshaked", "")) === "1",
            executed: raw ? raw.split(",") : []
        };
    }

    function saveState(state) {
        setProp("gallery_bridge_seq", String(state.seq));
        setProp("gallery_bridge_handshaked", state.handshaked ? "1" : "0");
        setProp("gallery_bridge_executed",
            state.executed.slice(-GALLERY_EXECUTED_MEMORY).join(","));
    }

    // Ask for exactly the fields this protocol needs. A field that is not
    // requested is not returned, and guessing at a default is how a status page
    // ends up describing something other than the real transfer.
    function linkQuery(base, pageIndex) {
        return copy({
            maxResults: GALLERY_PAGE_SIZE,
            startAt: pageIndex * GALLERY_PAGE_SIZE,
            bytesLoaded: true,
            bytesTotal: true,
            comment: true,
            enabled: true,
            eta: true,
            extractionStatus: true,
            finished: true,
            name: true,
            priority: true,
            running: true,
            saveTo: true,
            skipped: true,
            speed: true,
            status: true,
            url: true
        }, base);
    }

    // Walk a paged list to the end. Bounded on both axes: a page count and a
    // record count, so a growing list cannot make one tick run forever.
    function paged(namespace, method, base, maxPages, maxRecords) {
        var collected = [];
        for (var page = 0; page < maxPages; page++) {
            var chunk = callAPI(namespace, method, linkQuery(base, page));
            if (!chunk || !chunk.length) {
                break;
            }
            for (var i = 0; i < chunk.length; i++) {
                collected.push(chunk[i]);
                if (collected.length >= maxRecords) {
                    return collected;
                }
            }
            if (chunk.length < GALLERY_PAGE_SIZE) {
                break;
            }
        }
        return collected;
    }

    // Only Gallery's own packages. The prefix is the contract: anything else in
    // the download list belongs to the user and is out of scope.
    function galleryPackages() {
        var found = [];
        try {
            var packages = paged("downloadsV2", "queryPackages",
                {childCount: true, saveTo: true}, 20, 2000);
            for (var i = 0; i < packages.length; i++) {
                var entry = packages[i];
                var name = str(entry.name);
                if (name.indexOf(GALLERY_PACKAGE_PREFIX) !== 0) {
                    continue;
                }
                var uuid = safeId(entry.uuid);
                if (uuid === null) {
                    continue;
                }
                found.push({
                    uuid: uuid,
                    taskId: name.slice(GALLERY_PACKAGE_PREFIX.length),
                    saveTo: str(entry.saveTo)
                });
            }
        } catch (e) {
            // A query failure is reported as "no packages this tick"; the next
            // tick retries. It is never reported as "the task is gone".
        }
        return found;
    }

    function recordOf(link) {
        var linkId = safeId(link.uuid);
        // queryLinks.saveTo is not a reliable per-file path. Use JD's actual
        // DownloadLink sandbox, including plugin-selected filenames.
        var sandbox = linkId === null ? null : getDownloadLinkByUUID(linkId);
        var path = sandbox ? str(sandbox.getDownloadPath()) : "";
        return {
            link_id: linkId === null ? "" : linkId,
            name: str(link.name),
            status: sandbox ? str(sandbox.getFinalLinkStatus()) : str(link.status),
            finished: sandbox ? sandbox.isFinished() === true : false,
            running: sandbox ? sandbox.isRunning() === true : link.running === true,
            skipped: sandbox ? sandbox.isSkipped() === true : link.skipped === true,
            extraction_status: sandbox ? str(sandbox.getExtractionStatus()) : "",
            download_path: path,
            bytes_loaded: numberOrZero(link.bytesLoaded),
            bytes_total: numberOrZero(link.bytesTotal),
            bytes_total_verified: sandbox ? numberOrZero(sandbox.getBytesTotalVerified()) : 0,
            unsafe_id: linkId === null
        };
    }

    // One page of one job's snapshot. The identity set travels on the first
    // page: Gallery freezes it, so a later tick that sees a different set is a
    // changed manifest rather than a silently re-scoped task.
    function pagesOf(pkg) {
        var links = paged("downloadsV2", "queryLinks", {packageUUIDs: pkg.uuids || [pkg.uuid]},
            GALLERY_MAX_PAGES, GALLERY_PAGE_SIZE * GALLERY_MAX_PAGES);
        var records = [];
        var identity = [];
        var terminal = true;
        for (var i = 0; i < links.length; i++) {
            var record = recordOf(links[i]);
            records.push(record);
            identity.push(record.link_id);
            if (!record.finished && !record.skipped) {
                terminal = false;
            }
        }
        var totalPages = Math.max(1, Math.ceil(records.length / GALLERY_PAGE_SIZE));
        var pages = [];
        for (var page = 0; page < totalPages; page++) {
            pages.push({
                job_id: pkg.taskId,
                manifest_version: 0,
                snapshot_id: pkg.uuid,
                page_index: page,
                total_count: records.length,
                complete: terminal && page === totalPages - 1,
                expected: page === 0 ? identity : [],
                records: records.slice(page * GALLERY_PAGE_SIZE,
                    (page + 1) * GALLERY_PAGE_SIZE)
            });
        }
        return pages;
    }

    // Send a bounded slice of each job's pages per tick. The cursor is kept in
    // a property, because the next tick is a fresh evaluation of this script
    // and would otherwise start from page 0 forever. Gallery merges by page
    // index, so a pass spread over several ticks is one snapshot.
    function collectPages() {
        var packages = galleryPackages();
        var grouped = [], byTask = {};
        for (var p = 0; p < packages.length; p++) {
            var entry = packages[p];
            var key = "task:" + entry.taskId;
            if (!byTask[key]) {
                byTask[key] = {taskId: entry.taskId, uuids: [], uuid: ""};
                grouped.push(byTask[key]);
            }
            byTask[key].uuids.push(entry.uuid);
        }
        packages = grouped;
        var out = [];
        for (var i = 0; i < packages.length; i++) {
            var pkg = packages[i];
            pkg.uuid = pkg.uuids.slice().sort().join("+");
            var pages = pagesOf(pkg);
            var cursorName = "gallery_bridge_cursor_" + pkg.taskId;
            var start = readCount(cursorName, 0);
            if (start >= pages.length) {
                start = 0;
            }
            var sent = 0;
            while (sent < GALLERY_PAGES_PER_TICK && start + sent < pages.length) {
                out.push(pages[start + sent]);
                sent++;
            }
            var next = start + sent;
            setProp(cursorName, String(next >= pages.length ? 0 : next));
        }
        return out;
    }

    // addLinks.autoExtract belongs to CrawledLink, and the API move path does
    // not run the GUI's archive validation that transfers it into ArchiveSettings.
    // Persist and read back the archive policy before moving or starting links.
    // Use exact owned link IDs; empty selection means all links in some JD APIs.
    function disableArchiveExtraction(linkIds) {
        if (!linkIds.length) { return false; }
        try {
            var archives = callAPI("extraction", "getArchiveInfo", linkIds, []);
            if (!Array.isArray(archives)) { return false; }
            var ids = [];
            for (var i = 0; i < archives.length; i++) {
                var id = str(archives[i] && archives[i].archiveId);
                if (!id) { return false; }
                if (ids.indexOf(id) < 0) { ids.push(id); }
            }
            for (var j = 0; j < ids.length; j++) {
                if (callAPI("extraction", "setArchiveSettings", ids[j], {autoExtract: false}) !== true) {
                    return false;
                }
            }
            if (!ids.length) { return true; }
            var settings = callAPI("extraction", "getArchiveSettings", ids);
            if (!Array.isArray(settings) || settings.length !== ids.length) { return false; }
            for (var k = 0; k < ids.length; k++) {
                var verified = false;
                for (var n = 0; n < settings.length; n++) {
                    if (str(settings[n].archiveId) === ids[k] && settings[n].autoExtract === false) {
                        verified = true;
                    }
                }
                if (!verified) { return false; }
            }
            return true;
        } catch (e) {
            return false;
        }
    }

    // Only tasks explicitly returned by this Gallery may be advanced. Wait
    // until crawling finishes, then move exact packages without a global start.
    // The download list update is asynchronous: force only those packages on
    // a subsequent tick. A remembered start never overrides a user's JD pause.
    function advanceTasks(tasks) {
        if (!tasks || !tasks.length || globalAutoStart() !== false) { return; }
        var collecting = callAPI("linkgrabberv2", "isCollecting");
        var collector = collecting === false ? paged("linkgrabberv2", "queryPackages",
            {name: true, childCount: true}, 20, 2000) : [];
        var downloads = galleryPackages();
        for (var i = 0; i < tasks.length; i++) {
            var task = tasks[i];
            if (!task.start) { continue; }
            var name = GALLERY_PACKAGE_PREFIX + str(task.task_id);
            var moveIds = [], moveValid = true;
            for (var j = 0; j < collector.length; j++) {
                var pkg = collector[j];
                var id = safeId(pkg.uuid);
                if (str(pkg.name) !== name || id === null || !pkg.childCount) { continue; }
                var links = paged("linkgrabberv2", "queryLinks", {packageUUIDs: [id]},
                    GALLERY_MAX_PAGES, GALLERY_PAGE_SIZE * GALLERY_MAX_PAGES);
                if (!links.length || links.length !== Number(pkg.childCount)) { moveValid = false; continue; }
                var ids = [], valid = true;
                for (var k = 0; k < links.length; k++) {
                    var lid = safeId(links[k].uuid);
                    if (lid === null) { valid = false; break; }
                    ids.push(lid);
                }
                if (!valid) { moveValid = false; continue; }
                moveIds = moveIds.concat(ids);
            }
            if (moveValid && moveIds.length) {
                var stableKey = "gallery_bridge_collect_" + task.task_id;
                var signature = moveIds.slice().sort().join(",");
                if (str(prop(stableKey, "")) === signature) {
                    if (disableArchiveExtraction(moveIds)) {
                        callAPI("linkgrabberv2", "moveToDownloadlist", moveIds, []);
                    }
                } else {
                    setProp(stableKey, signature);
                }
            }
            for (var d = 0; d < downloads.length; d++) {
                var download = downloads[d];
                if (download.taskId !== str(task.task_id)) { continue; }
                var startedKey = "gallery_bridge_started_" + task.task_id + "_" + download.uuid;
                if (str(prop(startedKey, "")) === "1") { continue; }
                var pending = paged("downloadsV2", "queryLinks", {packageUUIDs: [download.uuid]},
                    GALLERY_MAX_PAGES, GALLERY_PAGE_SIZE * GALLERY_MAX_PAGES);
                var startIds = [];
                for (var n = 0; n < pending.length; n++) {
                    var nextId = safeId(pending[n].uuid);
                    if (nextId !== null && pending[n].enabled !== false && !pending[n].finished && !pending[n].skipped) {
                        startIds.push(nextId);
                    }
                }
                if (startIds.length) {
                    if (!disableArchiveExtraction(startIds)) { continue; }
                    callAPI("downloadsV2", "forceDownload", startIds, []);
                }
                setProp(startedKey, "1");
            }
        }
    }

    function execute(command) {
        var params = command.params || {};
        if (command.action === "add_links") {
            if (!str(params.links).trim()) {
                return {command_id: command.command_id, ok: false, detail: "missing share links"};
            }
            var query = {
                links: str(params.links),
                packageName: GALLERY_PACKAGE_PREFIX + str(command.job_id),
                assignJobID: true,
                autostart: false,
                autoExtract: false,
                deepDecrypt: false,
                overwritePackagizerRules: true
            };
            if (str(params.destinationFolder)) {
                query.destinationFolder = str(params.destinationFolder);
            }
            if (str(params.packagePassword)) {
                query.packagePassword = str(params.packagePassword);
            }
            var job = callAPI("linkgrabberv2", "addLinks", query);
            var jobId = job === null || job === undefined ? null : safeId(job.id);
            return {
                command_id: command.command_id,
                ok: jobId !== null,
                detail: jobId === null ? "JD did not return a collecting job id" : String(jobId)
            };
        }
        if (["pause", "resume", "remove"].indexOf(command.action) < 0) {
            return {command_id: command.command_id, ok: false, detail: "unsupported action " + str(command.action)};
        }
        var linkIds = [];
        var raw = params.link_ids || [];
        for (var i = 0; i < raw.length; i++) {
            var id = safeId(raw[i]);
            if (id === null) {
                return {
                    command_id: command.command_id,
                    ok: false,
                    detail: "an id in this command exceeds the safe integer range"
                };
            }
            linkIds.push(id);
        }
        var owned = [];
        var packages = galleryPackages();
        for (var p = 0; p < packages.length; p++) {
            if (packages[p].taskId !== str(command.job_id)) { continue; }
            var members = paged("downloadsV2", "queryLinks", {packageUUIDs: [packages[p].uuid]},
                GALLERY_MAX_PAGES, GALLERY_PAGE_SIZE * GALLERY_MAX_PAGES);
            for (var m = 0; m < members.length; m++) {
                var memberId = safeId(members[m].uuid);
                if (memberId !== null) { owned.push(memberId); }
            }
        }
        if (!linkIds.length) { linkIds = owned; }
        for (var q = 0; q < linkIds.length; q++) {
            if (owned.indexOf(linkIds[q]) < 0) {
                return {command_id: command.command_id, ok: false, detail: "link does not belong to this task"};
            }
        }
        if (!linkIds.length) {
            return {command_id: command.command_id, ok: false, detail: "task has no download links"};
        }
        if (command.action === "pause") {
            callAPI("downloadsV2", "setEnabled", false, linkIds, []);
        } else if (command.action === "resume") {
            if (!disableArchiveExtraction(linkIds)) {
                return {command_id: command.command_id, ok: false, detail: "archive auto-extraction could not be disabled"};
            }
            callAPI("downloadsV2", "setEnabled", true, linkIds, []);
            callAPI("downloadsV2", "forceDownload", linkIds, []);
        } else if (command.action === "remove") {
            callAPI("downloadsV2", "removeLinks", linkIds, []);
        } else {
            return {
                command_id: command.command_id,
                ok: false,
                detail: "unsupported action " + str(command.action)
            };
        }
        return {command_id: command.command_id, ok: true, detail: ""};
    }

    function runCommands(state, commands) {
        var results = [];
        if (!commands) {
            return results;
        }
        for (var i = 0; i < commands.length; i++) {
            var command = commands[i];
            var key = str(command.command_id);
            if (!key || state.executed.indexOf(key) >= 0) {
                // Same command_id delivered twice: JD acknowledges it without
                // running it again, which is what makes a retransmit safe.
                results.push({command_id: key, ok: true, detail: "duplicate"});
                continue;
            }
            state.executed.push(key);
            try {
                results.push(execute(command));
            } catch (e) {
                results.push({
                    command_id: key,
                    ok: false,
                    detail: String(e)
                });
            }
        }
        return results;
    }

    // The request budget in effect for this tick. JD's Event Scripter runs on
    // Rhino, where the Java runtime is reachable as `java`; that is what makes
    // a hard timeout possible at all. Where it is not reachable the honest
    // answer is 0: unbounded, and reported as unbounded.
    function requestBudget() {
        try {
            if (typeof java === "undefined" || java === null || !java.net || !java.lang || !java.io) {
                return 0;
            }
        } catch (e) {
            return 0;
        }
        return GALLERY_REQUEST_BUDGET_MS;
    }

    // Read the whole response body, refusing to be kept busy past the deadline
    // by a server that answers one byte at a time. Read timeouts bound each
    // blocking read; this bounds the total.
    function readAll(reader, deadline) {
        var chunks = [];
        var line = reader.readLine();
        while (line !== null) {
            if (new Date().getTime() > deadline) {
                throw "request budget exhausted";
            }
            chunks.push(String(line));
            line = reader.readLine();
        }
        return chunks.join("\n");
    }

    // The same form post postPage sends — token and payload fields, nothing
    // else — but issued on a connection with real socket timeouts and a
    // wall-clock deadline, so a hung server costs one bounded tick and not the
    // rest of the script's life.
    function javaPost(body, budget) {
        var deadline = new Date().getTime() + budget;
        var conn = new java.net.URL(GALLERY_URL).openConnection();
        try {
            conn.setConnectTimeout(budget);
            conn.setReadTimeout(budget);
            conn.setRequestMethod("POST");
            conn.setDoOutput(true);
            conn.setRequestProperty("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8");
            var bytes = new java.lang.String(body).getBytes("UTF-8");
            conn.setFixedLengthStreamingMode(bytes.length);
            var out = conn.getOutputStream();
            try {
                out.write(bytes, 0, bytes.length);
            } finally {
                out.close();
            }
            var code = conn.getResponseCode();
            var stream = code >= 400 ? conn.getErrorStream() : conn.getInputStream();
            if (stream === null) {
                return "";
            }
            try {
                return readAll(new java.io.BufferedReader(new java.io.InputStreamReader(stream, "UTF-8")), deadline);
            } finally {
                try { stream.close(); } catch (ignored) {}
            }
        } finally {
            try { conn.disconnect(); } catch (ignored) {}
        }
    }

    // One exchange request. A timeout or transport failure comes back as a
    // null response, which the callers already treat as "nothing arrived; keep
    // the ledger and try again next tick" — never as a delivered answer.
    function exchangePost(body) {
        var budget = requestBudget();
        if (budget > 0) {
            try {
                return javaPost(body, budget);
            } catch (e) {
                try {
                    log("Gallery bridge: request failed or exceeded the " + budget + " ms budget");
                } catch (ignored) {}
                return null;
            }
        }
        return postPage(GALLERY_URL, body);
    }

    function exchange(identityInfo) {
        var state = loadState();
        // The sequence is allocated before the payload is built: the first
        // request of a session is seq 1, and Gallery rejects 0 as malformed.
        state.seq = state.seq + 1;
        var payload = {
            version: GALLERY_PROTOCOL,
            bridge_id: identityInfo.device,
            session_id: identityInfo.session,
            seq: state.seq,
            ack: state.seq > 1 ? state.seq - 1 : 0,
            command_acks: [],
            command_results: [],
            pages: []
        };
        // The handshake names what this script can actually do, so Gallery does
        // not enable a capability the running script never had. It is re-sent on
        // every tick rather than once per session: the global auto-start switch
        // is one of the reported values, and Gallery's pre-check has to see the
        // setting as it is now, not as it was when the session opened. A user
        // who turns it back on in JD must not keep a move authorised by a stale
        // reading.
        payload.capabilities = {
            script_version: GALLERY_SCRIPT_VERSION,
            protocol_version: GALLERY_PROTOCOL,
            supports_commands: true,
            supports_pagination: true,
            supports_download_path: true,
            supports_snapshot: true,
            max_page_size: GALLERY_PAGE_SIZE,
            // The real budget of the request that is about to carry this
            // handshake. 0 is the plain postPage fallback: no hard timeout.
            request_timeout_ms: requestBudget(),
            // Reported every handshake, not only when it is false: Gallery has
            // to be able to tell "verified off" from "could not read".
            linkgrabber_auto_start_enabled: globalAutoStart()
        };

        payload.pages = collectPages();

        var body = "token=" + encodeURIComponent(GALLERY_TOKEN) +
            "&payload=" + encodeURIComponent(JSON.stringify(payload));
        var response = exchangePost(body);
        if (!response) {
            try { log("Gallery bridge: postPage returned empty response"); } catch (ignored) {}
            saveState(state);
            return;
        }
        var parsed = JSON.parse(response);
        if (!parsed || parsed.ok !== true) {
            try { log("Gallery bridge: exchange was rejected; check connection and pairing"); } catch (ignored) {}
            saveState(state);
            return;
        }
        state.handshaked = true;
        var results = runCommands(state, parsed.commands);
        if (results.length) {
            for (var i = 0; i < results.length; i++) {
                payload.command_acks.push(results[i].command_id);
            }
            payload.command_results = results;
            payload.pages = [];
            state.seq = state.seq + 1;
            payload.seq = state.seq;
            payload.ack = state.seq - 1;
            exchangePost("token=" + encodeURIComponent(GALLERY_TOKEN) +
                "&payload=" + encodeURIComponent(JSON.stringify(payload)));
        }
        saveState(state);
        advanceTasks(parsed.tasks);
    }

    try {
        exchange(identity());
    } catch (e) {
        // JD's exception can contain the HTTP request body, including the key.
        try { log("Gallery bridge: exchange failed; check connection, pairing and script permissions"); } catch (ignored) {}
    }
})();
